-- ============================================================
-- V1: fridge_schema 스키마 생성
--
-- 목적:
--   fridge_server 전용 PostgreSQL 스키마를 격리 생성한다.
--   PostgreSQL에서 SCHEMA는 MySQL의 DATABASE와 다르다.
--   동일 DB 인스턴스 내에서 스키마로 네임스페이스를 분리한다.
--
-- PostgreSQL vs MySQL 차이:
--   MySQL  : CREATE DATABASE = CREATE SCHEMA (동일 개념)
--   PostgreSQL : DATABASE > SCHEMA 계층 구조
--              → 스키마 격리는 CREATE SCHEMA로 처리
--
-- 주의:
--   한 번 적용된 이 파일은 절대 수정하지 않는다.
--   스키마 변경이 필요하면 V4, V5... 새 파일을 추가한다.
--
-- 작성: 승훈 / 2025-06-01
-- ============================================================

CREATE SCHEMA IF NOT EXISTS fridge_schema;